### ISSUE TITLE
ArchLinux ist falsch geschrieben

### ISSUE THREAD

**Issue by AdriDevelopsThings** [TornaxO7/my_configs#1]
Bitte zu ArschLinux ändern

**Comment by TornaxO7** [comment]
Awa, dafür hat Arch einen zu geilen _Arsch_ ;D

**Comment by AdriDevelopsThings** [comment]
Nein, das stimmt nicht.

Jetzt änder das!

**Comment by TornaxO7** [comment]
~~_NEIN NEIN NEIN NEIN!!!_~~
