### ISSUE TITLE
ico/svg files in awesome config

### ISSUE THREAD

**Issue by purplepalmdash** [TornaxO7/my_configs#2]
Could you please upload the ico files into repository? 

Like:   

```
image="/rest/favicons/ram.ico"
```
Thanks.

**Comment by TornaxO7** [comment]
Of course! Wait a little bit please

**Comment by TornaxO7** [comment]
I've updated the awesome-directory. It should work now out of the box. If you confront any bugs/issues, just create another issue :) 
By the way, sorry for the long waiting time, I needed to change some variables (which created some bugs...) and added a better `README.md`.
